demo = ""
description = "A robust, elegant theme for xypnox's blag"
homepage = "https://github.com/xypnox/blag"
license = "MIT"
min_version = "0.1.0"
name = "xyblag"

[extra]
blog_menu = [
  {url = "$BASE_URL", name = "Home"},
  {url = "$BASE_URL/upcoming", name = "Upcoming Posts"},
  {url = "$BASE_URL/categories", name = "Categories"},
  {url = "$BASE_URL/tags", name = "Tags"},
  {url = "$BASE_URL/about", name = "About"},
  {url = "$BASE_URL/notes", name = "Notes"},
]

[author]
homepage = "https://www.xypnox.com"
name = "xypnox"

[original]
author = "Vincent Prouillet"
homepage = "https://zola-even.netlify.com"
repo = "https://github.com/getzola/even"
